/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Arctic Precision design system — see design/arctic_precision/DESIGN.md
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#bcc9cd',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#869397',
        'outline-variant': '#3c494c',
        'surface-tint': '#4cd7f4',
        primary: '#57e0fd',
        'on-primary': '#00363f',
        'primary-container': '#2ec4e0',
        'on-primary-container': '#004d5a',
        'inverse-primary': '#006879',
        secondary: '#ffed66',
        'on-secondary': '#373100',
        'secondary-container': '#e5d100',
        'on-secondary-container': '#625900',
        tertiary: '#cfcfd0',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#b3b4b4',
        'on-tertiary-container': '#444646',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
        success: '#4ade80',
        warning: '#ffed66',
      },
      fontFamily: {
        display: ['Montserrat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['Space Mono', 'monospace'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      boxShadow: {
        frost: '0 20px 40px -10px rgba(0, 20, 25, 0.3)',
      },
      backdropBlur: {
        glass: '12px',
      },
    },
  },
  plugins: [],
}
